name: Update device
on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    name: Update device
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: LoRa FUOTA Updater
        uses: ignacioFernandez1/lora-fuota-updater@v0.1.1-alpha
        with:
          LORASERVER_IP: "192.168.1.14"
          LORASERVER_URL: "http://192.168.1.14"
          LORASERVER_MQTT_PORT: 1883
          LORASERVER_API_PORT: 8090
          LORASERVER_API_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjNkM2Y1MWYxLTg3YjYtNDkwZC04NTRkLTFjNzQyNjNkMWY1NSIsInR5cCI6ImtleSJ9.89rZAeIIMd_NaAtuH6STrizLDtbRnVjS10MpRCDmW2k"
          LORASERVER_TENANT_ID: "52f14cd4-c6f1-4fbd-8f87-4025e1d49242"
          LORASERVER_DOWNLINK_DR: 5
          LORASERVER_DOWNLINK_FREQ: 869525000
          LORASERVER_APP_ID: "b43d35e7-d236-471d-ad3b-19698d294f12"
          DEVICE_EUI: '["c5c65c3303799380", "cf80cc3cee74cd17"]'